### sign up
POST http://localhost:3000/users/signup
Content-Type: application/json

{
  "name": "John Doe",
  "username":"johndoe8",
  "email": "johnDoe8@gmail.com",
  "password": "JohnDoe123"
}

### sign in
POST http://localhost:3000/users/signin
Content-Type: application/json

{
  "username":"johndoe8",
  "password": "JohnDoe123"
}

### Get all users
GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG5kb2U4IiwiaWF0IjoxNjY4NjI5NDQ1LCJleHAiOjE2NjkyMzQyNDV9.QT4CtV6Cmp18dK93z-I7h2hKttVSxRhfJwIMgUZClPA

### Ger user by id 
GET http://localhost:3000/users/10

### Create a user
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "John Doe",
  "username":"johndoe11",
  "email": "johnDoe11@gmail.com",
  "password": "1234567"
}


### Update a user
PATCH http://localhost:3000/users/10
Content-Type: application/json

{
  "name": "John Doe5"
}

### Delete a user
DELETE http://localhost:3000/users/9
