### Get all files
GET http://localhost:3000/files
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG5kb2U4IiwiaWF0IjoxNjY4OTU5MjYwLCJleHAiOjE2Njk1NjQwNjB9.F2RGC_wKl6H-6Qo-3MVqZJShGeclvf5ARM5rq3zvgfY

### Get one file
GET http://localhost:3000/files/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG5kb2U4IiwiaWF0IjoxNjY4OTU5MjYwLCJleHAiOjE2Njk1NjQwNjB9.F2RGC_wKl6H-6Qo-3MVqZJShGeclvf5ARM5rq3zvgfY