### Get all repos
GET http://localhost:3000/repos
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG5kb2UyMCIsImlhdCI6MTY2OTU4MDg1NywiZXhwIjoxNjcwMTg1NjU3fQ.sdwE4dMMIeonka5J4eD_vJYvl3m2HQ50ZxssNRwTvXA
### Get a repo
GET http://localhost:3000/repos/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG5kb2UyMCIsImlhdCI6MTY2OTU4MDg1NywiZXhwIjoxNjcwMTg1NjU3fQ.sdwE4dMMIeonka5J4eD_vJYvl3m2HQ50ZxssNRwTvXA

### favorite a repo
POST http://localhost:3000/repos/favorites/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG5kb2UyMCIsImlhdCI6MTY2OTU4MDg1NywiZXhwIjoxNjcwMTg1NjU3fQ.sdwE4dMMIeonka5J4eD_vJYvl3m2HQ50ZxssNRwTvXA

### unfavorite a repo
PATCH http://localhost:3000/repos/favorites/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG5kb2UyMCIsImlhdCI6MTY2OTU4MDg1NywiZXhwIjoxNjcwMTg1NjU3fQ.sdwE4dMMIeonka5J4eD_vJYvl3m2HQ50ZxssNRwTvXA


### get favorite repos
GET http://localhost:3000/repos/favorites
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG5kb2UyMCIsImlhdCI6MTY2OTU4MDg1NywiZXhwIjoxNjcwMTg1NjU3fQ.sdwE4dMMIeonka5J4eD_vJYvl3m2HQ50ZxssNRwTvXA


### toggle pin a repo
PATCH  http://localhost:3000/repos/pins/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG5kb2UyMCIsImlhdCI6MTY2OTU4MDg1NywiZXhwIjoxNjcwMTg1NjU3fQ.sdwE4dMMIeonka5J4eD_vJYvl3m2HQ50ZxssNRwTvXA


### get pin repos
GET http://localhost:3000/repos/pins
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG5kb2UyMCIsImlhdCI6MTY2OTU4MDg1NywiZXhwIjoxNjcwMTg1NjU3fQ.sdwE4dMMIeonka5J4eD_vJYvl3m2HQ50ZxssNRwTvXA


### Create a repo
POST http://localhost:3000/repos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG5kb2UyMCIsImlhdCI6MTY2OTU4MDg1NywiZXhwIjoxNjcwMTg1NjU3fQ.sdwE4dMMIeonka5J4eD_vJYvl3m2HQ50ZxssNRwTvXA

{
  "name": "repo",
  "content":"content"
}

### Update a repo
PATCH  http://localhost:3000/repos/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG5kb2UyMCIsImlhdCI6MTY2OTU4MDg1NywiZXhwIjoxNjcwMTg1NjU3fQ.sdwE4dMMIeonka5J4eD_vJYvl3m2HQ50ZxssNRwTvXA

{
  "content":"new content 2"
}

### Delete a repo
DELETE http://localhost:3000/repos/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG5kb2UyMCIsImlhdCI6MTY2OTU4MDg1NywiZXhwIjoxNjcwMTg1NjU3fQ.sdwE4dMMIeonka5J4eD_vJYvl3m2HQ50ZxssNRwTvXA